# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mgorshkov/Work/join_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mgorshkov/Work/join_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/mgorshkov/Work/join_server/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mgorshkov/Work/join_server/CMakeFiles /home/mgorshkov/Work/join_server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mgorshkov/Work/join_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named join_server_test

# Build rule for target.
join_server_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 join_server_test
.PHONY : join_server_test

# fast build rule for target.
join_server_test/fast:
	$(MAKE) -f CMakeFiles/join_server_test.dir/build.make CMakeFiles/join_server_test.dir/build
.PHONY : join_server_test/fast

#=============================================================================
# Target rules for targets named join_server_lib

# Build rule for target.
join_server_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 join_server_lib
.PHONY : join_server_lib

# fast build rule for target.
join_server_lib/fast:
	$(MAKE) -f CMakeFiles/join_server_lib.dir/build.make CMakeFiles/join_server_lib.dir/build
.PHONY : join_server_lib/fast

#=============================================================================
# Target rules for targets named join_server

# Build rule for target.
join_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 join_server
.PHONY : join_server

# fast build rule for target.
join_server/fast:
	$(MAKE) -f CMakeFiles/join_server.dir/build.make CMakeFiles/join_server.dir/build
.PHONY : join_server/fast

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/join_server.dir/build.make CMakeFiles/join_server.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/join_server.dir/build.make CMakeFiles/join_server.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/join_server.dir/build.make CMakeFiles/join_server.dir/server.cpp.s
.PHONY : server.cpp.s

session.o: session.cpp.o

.PHONY : session.o

# target to build an object file
session.cpp.o:
	$(MAKE) -f CMakeFiles/join_server.dir/build.make CMakeFiles/join_server.dir/session.cpp.o
.PHONY : session.cpp.o

session.i: session.cpp.i

.PHONY : session.i

# target to preprocess a source file
session.cpp.i:
	$(MAKE) -f CMakeFiles/join_server.dir/build.make CMakeFiles/join_server.dir/session.cpp.i
.PHONY : session.cpp.i

session.s: session.cpp.s

.PHONY : session.s

# target to generate assembly for a file
session.cpp.s:
	$(MAKE) -f CMakeFiles/join_server.dir/build.make CMakeFiles/join_server.dir/session.cpp.s
.PHONY : session.cpp.s

tablestorage.o: tablestorage.cpp.o

.PHONY : tablestorage.o

# target to build an object file
tablestorage.cpp.o:
	$(MAKE) -f CMakeFiles/join_server_lib.dir/build.make CMakeFiles/join_server_lib.dir/tablestorage.cpp.o
.PHONY : tablestorage.cpp.o

tablestorage.i: tablestorage.cpp.i

.PHONY : tablestorage.i

# target to preprocess a source file
tablestorage.cpp.i:
	$(MAKE) -f CMakeFiles/join_server_lib.dir/build.make CMakeFiles/join_server_lib.dir/tablestorage.cpp.i
.PHONY : tablestorage.cpp.i

tablestorage.s: tablestorage.cpp.s

.PHONY : tablestorage.s

# target to generate assembly for a file
tablestorage.cpp.s:
	$(MAKE) -f CMakeFiles/join_server_lib.dir/build.make CMakeFiles/join_server_lib.dir/tablestorage.cpp.s
.PHONY : tablestorage.cpp.s

tablestorage_test.o: tablestorage_test.cpp.o

.PHONY : tablestorage_test.o

# target to build an object file
tablestorage_test.cpp.o:
	$(MAKE) -f CMakeFiles/join_server_test.dir/build.make CMakeFiles/join_server_test.dir/tablestorage_test.cpp.o
.PHONY : tablestorage_test.cpp.o

tablestorage_test.i: tablestorage_test.cpp.i

.PHONY : tablestorage_test.i

# target to preprocess a source file
tablestorage_test.cpp.i:
	$(MAKE) -f CMakeFiles/join_server_test.dir/build.make CMakeFiles/join_server_test.dir/tablestorage_test.cpp.i
.PHONY : tablestorage_test.cpp.i

tablestorage_test.s: tablestorage_test.cpp.s

.PHONY : tablestorage_test.s

# target to generate assembly for a file
tablestorage_test.cpp.s:
	$(MAKE) -f CMakeFiles/join_server_test.dir/build.make CMakeFiles/join_server_test.dir/tablestorage_test.cpp.s
.PHONY : tablestorage_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... join_server_test"
	@echo "... join_server_lib"
	@echo "... join_server"
	@echo "... package"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... session.o"
	@echo "... session.i"
	@echo "... session.s"
	@echo "... tablestorage.o"
	@echo "... tablestorage.i"
	@echo "... tablestorage.s"
	@echo "... tablestorage_test.o"
	@echo "... tablestorage_test.i"
	@echo "... tablestorage_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

